### ISSUE TITLE
eclipseでサーブレットの自動生成するのが困難

### ISSUE THREAD

**Issue by Mee1123** [cs-u-gakugei-ac-jp/java_app_sample#1]
プロジェクトの導入時にwebアプリであることを指定しなければならない様です。

またサーバークラスコンテナApacheTomcatを導入しないと補完が上手くいかないです。
入れたら入れたで、gitにプッシュするのが大変です。

**Comment by kawaguchisan** [comment]
Eclipse 使わないので、よくわからないです。
